name: Test action

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run action
        id: hello
        uses: ./
        with:
          who-to-greet: Antonio

      - name: Verify result
        run: |
          expected="Hello, Antonio!"
          actual="${{ steps.hello.outputs.greeting }}"

          if [ "$actual" != "$expected" ]; then
            echo "Expected: $expected"
            echo "Actual: $actual"
            exit 1
          fi
