name: Test action

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Test default input
        uses: ./

      - name: Test custom input
        uses: ./
        with:
          who-to-greet: Antonio
