name: Test action

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run action @v1.0.0
        id: hello
        uses: fferegrino/learning-actions@v1.0.0
        with:
          who-to-greet: Antonio

      - name: Run action @v2.0.0
        id: hola
        uses: fferegrino/learning-actions@v2.0.0
        with:
          who-to-greet: Antonio
          language: ES

      - name: Run action @main
        id: latest
        uses: fferegrino/learning-actions@main
        with:
          who-to-greet: Antonio
          language: ES

      - name: Verify result
        run: |
          expected="¡Hola, Antonio!"
          actual="${{ steps.hola.outputs.greeting }}"

          if [ "$actual" != "$expected" ]; then
            echo "Expected: $expected"
            echo "Actual: $actual"
            exit 1
          fi
